### ISSUE TITLE
Consider Making `ArrayPoolExtensions` Public

### ISSUE THREAD

**Issue by Mike-E-angelo** [NetFabric/NetFabric.Hyperlinq#372]
Consider the following class:

https://github.com/DragonSpark/Framework/blob/e43394bb88b223a2c8726ce08da02745b5532631/DragonSpark/Model/Sequences/Memory/Lease.cs

It makes use of a generic `IMemoryOwner` implementation, and I have been using it with an older version of Hyperlinq.

As of `3.0.0-beta45` however, it appears that `ValueMemoryOwner` is used, and now sending it to the constructor above as designed will end up in a boxed allocation.  

So, I am looking for a way to instantiate the `ValueMemoryOwner`.  Unfortunately, its constructor is `internal`.  Additionally, the only way of instantiating one appears to be via `ArrayPoolExtensions` and this is also internal.

Would it be worth exploring the possibility of exposing these points of concern as `public`?  Is there another approach I should consider?

Thank you for any assistance provided.

**Comment by Mike-E-angelo** [comment]
I have a further thought/consideration around this.

Consider introducing a new interface as such:

```
public interface IMemoryOwnerProducer<out T, V> where T : IMemoryOwner<V>
{
	T Get(in uint size);
}
```

An implementation would be like this:

```
public readonly struct Owner<T> : IMemoryOwner<T>
{
	readonly ArrayPool<T> _pool;
	readonly T[]          _store;

	public Owner(ArrayPool<T> pool, T[] store, Memory<T> memory)
	{
		Memory = memory;
		_pool  = pool;
		_store = store;
	}

	public Memory<T> Memory { get; }

	public void Dispose()
	{
		_pool.Return(_store);
	}
}

sealed class Owners<T> : IMemoryOwnerProducer<Owner<T>, T>
{
	public static Owners<T> Default { get; } = new Owners<T>();

	Owners() : this(ArrayPool<T>.Shared) {}

	readonly ArrayPool<T> _pool;

	public Owners(ArrayPool<T> pool) => _pool = pool;

	public Owner<T> Get(in uint size)
	{
		var requested = (int)size;
		var store     = _pool.Rent(requested);
		return new(_pool, store, store.AsMemory()[..requested]);
	}
}```

Then in addition to the `ToArray(ArrayPool)` method, introduce a `ToArray(IMemoryOwnerProducer<T,V>)` method which would use the produced `IMemoryOwner` and return it back to caller.

This way you could keep everything internal while providing a way for callers to get their own memory owners.

**Comment by aalmada** [comment]
The change in the type returned by `ToArray()` from `IMemoryOwner<>` to `ValueMemoryOwner<>` was a breaking change. I don't like to make these but that's why it's still a beta.

Before I was using `MemoryPool<>.Rent()` that returns `IMemoryOwner<>` which is disposable. I like this API because the caller only has to dispose of the result to return the rented memory to the pool. It keeps internal references to the pool and the rented memory. Otherwise, when using `ArrayPool<>.Rent()` the caller has to manage these two references.

What I don't like about `MemoryPool<>.Rent()` is that it allocates the result in the heap and its `Memory` property references all the memory rented in this operation, which can be larger than requested. To work around this, Hyperlinq uses `ArrayPool<>.Rent()` internally and returns `ValueMemoryOwner<>`, a disposable value type, for which the `Memory` property references only the used part of the rented memory. This way, the `Length` property has the expected value for the given `ToArray()` operation.

`ValueMemoryOwner<>` now has an extra `Rented` property that references the entire rented memory as an array. This can be passed as a parameter for `ICollection<>.CopyTo()`. As we saw in #373, not having this resulted in a big performance penalty.

The `ValueMemoryOwner<>` has to be public so that it can be returned without boxing but I kept its constructor internal because the users are not supposed to create instances. Just like with `MemoryPool<>.Rent()` where you don't even know the type of the instance returned.

I'm now realising that there's one dangerous issue. Value types are copied when assigned, passed as parameters, or returned by a method. When more than one copy of `ValueMemoryOwner<>` is disposed of, it will try to return the same rented memory on each disposal. 😞 In these cases, `IMemoryOwner<>` should be used so that it's boxed into a reference type. Unfortunately, there's no way to enforce this. Should I make it a reference type? Each instance uses very little memory and its use will be much safer. What do you think?

**Comment by Mike-E-angelo** [comment]
> What I don't like about MemoryPool<>.Rent() is that it allocates the result in the heap and its Memory property references all the memory rented in this operation, which can be larger than requested

Nodding along.  I prefer the `ArrayPool` as it seems much more performant.  However, `ArrayPool.Rent` does the same, correct?  It, too, allocates its arrays in set sizes so the actual array you get back is usually larger than what is requested.

> Value types are copied when assigned, passed as parameters, or returned by a method.

Are you sure this is the case when it's a `readonly struct`, @aalmada?  FWIW I _only_ use `readonly struct`'s because of the problems you outlined and much much more. :)  Anything other than this when it comes to `struct`s, I get nervous because there seems to be a lot more going on that is necessary.

My recommendation is to aim for a solution that uses `readonly struct` instead and see if you can work out something from there.  From my previous testing, there is no penalty when using these suckers, which is why I use them everywhere. :)

BTW this is what I hate about performance-based development/solutions.  It always seems you solve one problem and introduce another. 😭

**Comment by aalmada** [comment]
@Mike-E-angelo 

`readonly struct` only prevents defensive copies: https://www.infoq.com/news/2018/07/structs-performance-csharp/

`ref struct` prevents boxing: http://www.devsanon.com/c/c-7-2-introducing-ref-struct/

But, as a rule, all value types are passed by copy.

Given this, I decided to go back to return `IMemoryOwner<>`. Calling `ToArray()` with a parameter of type `ArrayPool` now allocates 40 bytes on the heap. I was trying to avoid it but It's safer this way. 

While doing this I did a complete review of all `ToArray()` cases. You can find it in #378.

Here are the latest benchmarks:

![image](https://user-images.githubusercontent.com/534533/132062224-71ed321a-2ca2-49d1-9f2e-de9c659e6c6f.png)

Let me know what you think.

**Comment by Mike-E-angelo** [comment]
> But, as a rule, all value types are passed by copy.

I will have to dig up some benchmarks, or maybe make new ones.  I recall doing some testing where `readonly structs` were faster in passing parameters between methods than references. 😲

> Let me know what you think.

Yeah it's good from my side.  Any allocations is not ideal, but now consider that I am in EFCore land where the typical invocation for the simplest of operations will yield anywhere from 2-4KB of space. 😞

The other consideration is that maybe it yields 40B now, but in a future .NET it doesn't. :)

**Comment by Mike-E-angelo** [comment]
Nope I am living in fairytale land here.

[From here](https://github.com/DragonSpark/Framework/blob/d77e1374d33d21b4f796e248148976f4300a750f/DragonSpark.Testing/Model/Selection/SelectionTests.cs):


| Method |     Mean |     Error |   StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|------- |---------:|----------:|---------:|------:|--------:|-------:|----------:|
|  Class | 43.64 ns |  6.257 ns | 0.343 ns |  1.00 |    0.00 | 0.0048 |      40 B |
|  Write | 87.70 ns |  5.808 ns | 0.318 ns |  2.01 |    0.02 |      - |         - |
|   Read | 87.49 ns | 16.726 ns | 0.917 ns |  2.00 |    0.03 |      - |         - |

I am not sure what I was thinking, or probably something funny in the tests.  Ah I think I know what it is... the tests I was running was using the `in` keyword.  That keeps it from copying, right?

My problem is that everything in my framework is predicated on the [this selector](https://github.com/DragonSpark/Framework/blob/d77e1374d33d21b4f796e248148976f4300a750f/DragonSpark/Model/Selection/ISelect.cs).  I could make it `in` but as you know that doesn't really agree with `Func<>`s.  Maybe there might be some clever adaption that I could employ.

Anyways, add that to the pile of raging fires in my world. 😅😭

**Comment by Mike-E-angelo** [comment]
Here are those same tests with the `in` keyword:

| Method |     Mean |     Error |   StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|------- |---------:|----------:|---------:|------:|--------:|-------:|----------:|
|  Class | 44.20 ns | 23.750 ns | 1.302 ns |  1.00 |    0.00 | 0.0048 |      40 B |
|  Write | 41.84 ns |  1.127 ns | 0.062 ns |  0.95 |    0.03 |      - |         - |
|   Read | 44.54 ns |  1.476 ns | 0.081 ns |  1.01 |    0.03 |      - |         - |

So maybe that is what I am thinking about.  Interesting that the writable struct is faster than the `readonly struct` by a smidge.

**Comment by Mike-E-angelo** [comment]
So scratch my previous posts (I deleted them).  The way I was testing/benchmarking was not apples-to-apples.

I spent some time with the `in` parameter and `readonly struct` and looks like I was straight up wrong on all accounts.  Even with the `in` parameter the structs are slower when passed between methods:

([using these benchmarks](https://github.com/DragonSpark/Framework/blob/f6fb7874fffae1e359b9001a42ef07aaa6da4254/DragonSpark.Testing/Model/Selection/SelectionTests.cs#L59-L142))

|          Method |    EnvironmentVariables |     Mean |    Error |   StdDev | Ratio | RatioSD |  Gen 0 | Allocated |
|---------------- |------------------------ |---------:|---------:|---------:|------:|--------:|-------:|----------:|
| ReferenceSelect |                   Empty | 22.31 ns | 0.500 ns | 0.331 ns |  1.00 |    0.00 | 0.0048 |      40 B |
|     WriteSelect |                   Empty | 39.14 ns | 0.629 ns | 0.374 ns |  1.76 |    0.03 |      - |         - |
|      ReadSelect |                   Empty | 39.13 ns | 0.618 ns | 0.409 ns |  1.75 |    0.03 |      - |         - |
|         ClassIn |                   Empty | 25.94 ns | 0.440 ns | 0.262 ns |  1.17 |    0.02 | 0.0048 |      40 B |
|         WriteIn |                   Empty | 36.00 ns | 0.320 ns | 0.168 ns |  1.62 |    0.02 |      - |         - |
|          ReadIn |                   Empty | 35.80 ns | 0.223 ns | 0.147 ns |  1.61 |    0.02 |      - |         - |
|                 |                         |          |          |          |       |         |        |           |
| ReferenceSelect | COMPlus_JitAlignLoops=1 | 23.01 ns | 0.427 ns | 0.254 ns |  1.00 |    0.00 | 0.0048 |      40 B |
|     WriteSelect | COMPlus_JitAlignLoops=1 | 39.22 ns | 0.393 ns | 0.260 ns |  1.70 |    0.02 |      - |         - |
|      ReadSelect | COMPlus_JitAlignLoops=1 | 39.16 ns | 0.582 ns | 0.385 ns |  1.70 |    0.02 |      - |         - |
|         ClassIn | COMPlus_JitAlignLoops=1 | 26.01 ns | 0.695 ns | 0.459 ns |  1.13 |    0.02 | 0.0048 |      40 B |
|         WriteIn | COMPlus_JitAlignLoops=1 | 35.59 ns | 0.283 ns | 0.148 ns |  1.55 |    0.02 |      - |         - |
|          ReadIn | COMPlus_JitAlignLoops=1 | 35.72 ns | 0.197 ns | 0.117 ns |  1.55 |    0.02 |      - |         - |

(I use `COMPlus_JitAlignLoops` because I have been traumatized by readings in the past that were deviating up to 30% because of loop alignments :P )

So, looks like it's a choice between slower runtime with lesser GC or faster runtime with the GC sweep tax.  Pick your poison :P

To me it seems better (and cleaner, because garbage and all 😏) to choose the path that is slower with less allocations.  But that's me.

**Comment by Mike-E-angelo** [comment]
Heya @aalmada I am *finally* starting to take a look at this now, apologies for the delay.  I see that ArrayPoolExtensions is still internal.  Any suggestions on how I would go about making my own `Lease`?  I am currently using this:

https://github.com/DragonSpark/Framework/blob/projects/Starbeam/DragonSpark/Model/Sequences/Memory/Leases.cs

**Comment by aalmada** [comment]
@Mike-E-angelo 
The latest version (beta46) already has a `Lease<>` type: https://github.com/NetFabric/NetFabric.Hyperlinq/blob/main/NetFabric.Hyperlinq/Lease.cs
The constructor is `internal` because I was thinking that it would be only used as a result for `ToArray()` operations. Do you want to use it in other scenarios?

**Comment by aalmada** [comment]
@Mike-E-angelo Version [beta47](https://www.nuget.org/packages/NetFabric.Hyperlinq/3.0.0-beta47) is now available with the `Lease<>` constructor as public.

**Comment by Mike-E-angelo** [comment]
Correct.  Ideally, I would like to remove mine now in place of yours since they are basically the same.  I am not looking for the constructor to be made public but the `ArrayPoolExtensions.Lease` method.  Although now I see you made `Lease` public as well.  

I could work with that but wanted to check in with you first. Are you able to make the `ArrayPoolExtensions.Lease` method `public` (and the `Lease` constructor back to `internal`)?  It's basically a factory method and preferred.

**Comment by aalmada** [comment]
@Mike-E-angelo Doh! You're right! It makes more sense to make `ArrayPoolExtensions.Lease()` public than it is to make the `Lease<>` constructor public. I'll publish a new version later at the end of the afternoon.

**Comment by aalmada** [comment]
@Mike-E-angelo Now available on version [beta48](https://www.nuget.org/packages/NetFabric.Hyperlinq/3.0.0-beta48)

**Comment by Mike-E-angelo** [comment]
Awesome!  Thank you @aalmada.  I appreciate you taking the time to get this done.  I will close this issue for now and check back in with any progress/need to reopen.  Thanks again for your efforts. 👍

**Comment by Mike-E-angelo** [comment]
I've renamed my component... LEASING 😆

https://github.com/DragonSpark/Framework/blob/projects/Starbeam/DragonSpark/Model/Sequences/Memory/Leasing.cs

(Whenever I do a significant rename, I play this in my head:)
https://youtu.be/GyIzzBf18pg

**Comment by Mike-E-angelo** [comment]
Living the dream now:

![](https://bit.ly/3zOIRyp)
